Ft reporter dashboard
BuildForSDG/Team-006-Frontend pull request #19
Opened 2020-05-16 10:49 UTC by ArinzeOkorji

## Description
Summary of the change and relevant motivation and context. 
Created a `reporter-dashboard` component within its own lazy-loaded module as well as a `reporter` service in a core folder, created `navbar` component within a shared module, added the `Fontawesome icon library` and tested the created components and service within their respective `.spec.ts` files. Also, included a router for the `reporter-dashboard` component.

Dependencies that are required for this change.
- "@fortawesome/angular-fontawesome": "^0.5.0",
- "@fortawesome/fontawesome-svg-core": "^1.2.21",
- "@fortawesome/free-solid-svg-icons": "^5.13.0",

Fixes #15 

## How Has This Been Tested?
Performed isolated unit tests on the created components and service in their respective `.spec.ts` files using karma/jasmine. 
Each test was done against the created methods and the tests delivered expected output.

## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [ x] New and existing unit tests pass locally with my changes

2020-05-16 14:27 UTC, dave-ok requested changes
@ArinzeOkorji  This is some really cool work! But there are a couple of observations I would like to point out
- to help with lint errors / format errors like `.scss` files add this script to npm scripts in package.json `"lint:fix": "ng lint --fix=true && prettier --write ."` and run it (i.e npm run lint:fix) before pushing your commits to lint and fix errors.
- I ran this PR locally and it renders well on mobile layout but it is not responsive in larger layouts it clips of on the right.

2020-05-17 02:09 UTC, ifeLight submitted a review, later dismissed

2020-05-17 03:32 UTC, dave-ok commented
@ArinzeOkorji Great work! I see prettier fixed a lot of the issues. I am approving this PR but please note the following suggestions before you create a new PR. 

- I noticed that you disabled prettier formatting for `SASS, SCSS` and `CSS`. I don't think that was the problem with the subsequent commits failing on codacy and this defeats the essence of prettier in your workspace. The error from my observation of your commits is from not having a newline at the end of the `SCSS` files, which is strange because all linters and prettier always enforce the rule that each file must have a newline at the end, and running `npm run lint:fix` should have corrected this or any other potential errors. This isn't necessary and prettier should work you just fine. But, if all these fail, you could try setting `"files.insertFinalNewline": true` to force a new line at the end of each file.

- I also noticed that you seem to have the VSCode prettier extension installed, but disabled formatting of `SCSS` files on save. This is not necessary and you should remove it and ensure you have this setting `"editor.formatOnSave": true,`

- Also, try installing the [TSLint VSCode Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) and set `"editor.codeActionsOnSave": { "source.fixAll.tslint": true }` in your workspace for automatically running TSlint and prettier on save.

2020-05-17 03:32 UTC, dave-ok submitted a review, later dismissed

2020-05-17 15:35 UTC, dave-ok approved these changes
@ArinzeOkorji  Awesome stuff! The device width restriction for reporters works perfectly

2020-05-17 20:50 UTC, ifeLight approved these changes

2020-05-21 10:33 UTC, dallintine approved these changes

2020-05-21 10:33 UTC, merged