Ft reporter authentication
BuildForSDG/Team-006-Frontend pull request #23
Opened 2020-05-23 11:53 UTC by ArinzeOkorji

## Description
Summary of the change and relevant motivation and context: Created a signup page for reporters to create new accounts on the platform. New users would then be asked to confirm their details before it gets sent to the DB and they get routed to the **reporter dashboard**. 

Fixes #13 

## How Has This Been Tested?
Wrote isolated unit tests against services and components to ensure methods were called and components were created.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [x ] New and existing unit tests pass locally with my changes

2020-05-23 12:17 UTC, ifeLight submitted a review, later dismissed

2020-05-23 18:00 UTC, ifeLight submitted a review, later dismissed

2020-05-23 18:11 UTC, dave-ok requested changes
@ArinzeOkorji The build is failing on Travis. When I checked I saw that the "auth.service.spec.ts" was failing, because it seems you changed the constructor function parameters for the class AuthService from 4 to 3. To avoid this, always run lint and test locally before you push. If you run the tests and lint locally you should see the errors there as well

2020-05-23 21:38 UTC, dave-ok approved these changes
@ArinzeOkorji This is awesome! Your tests look very robust. And thanks for correcting path to the build folder

2020-05-24 14:32 UTC, ifeLight approved these changes

2020-05-26 10:46 UTC, dallintine approved these changes

2020-05-26 10:47 UTC, merged